
services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  web:
    build: .
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql+pymysql://${DB_USER}:${DB_PASS}@db:3306/${DB_NAME}
      FLASK_APP: app:create_app
      FLASK_DEBUG: ${FLASK_DEBUG}
    ports:
      - '5000:5000'
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  db_data:
